laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('empresa', 'EmpresaController@index')->name('empresa');
    Route::get('produtos/aplicacoes/{id?}', 'ProdutosController@aplicacoes')->name('produtos.aplicacoes');
    // Route::get('produtos/segmento/{produtos_segmento}', 'ProdutosController@segmento')->name('produtos.segmento');
    Route::get('produtos/{produtos_linha?}', 'ProdutosController@index')->name('produtos');
    Route::get('produtos/{produtos_linha}/{produto_slug}', 'ProdutosController@show')->name('produtos.show');
    Route::get('servicos/{servico_slug?}', 'ServicosController@index')->name('servicos');
    Route::get('cases-e-obras/{case_slug?}', 'CasesController@index')->name('cases');
    Route::get('clientes/{clientes_categoria?}', 'ClientesController@index')->name('clientes');
    Route::get('tabelas', 'TabelasController@index')->name('tabelas');
    Route::get('blog/{post_slug?}', 'BlogController@index')->name('blog');
    Route::get('blog/c/{blog_categoria}', 'BlogController@categoria')->name('blog.categoria');
    Route::get('blog/a/{ano}/{mes}', 'BlogController@arquivo')->name('blog.arquivo');
    Route::post('blog-comentario', 'BlogController@comentario');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::get('pesquisa-de-satisfacao', 'PesquisaController@index')->name('pesquisa');
    Route::post('pesquisa-de-satisfacao', 'PesquisaController@post')->name('pesquisa.post');
    Route::get('trabalhe-conosco', 'TrabalheConoscoController@index')->name('trabalhe');
    Route::post('trabalhe-conosco', 'TrabalheConoscoController@post')->name('trabalhe.post');
    Route::get('catalogo/{id}', 'ProdutosController@catalogo')->name('catalogo');
    Route::post('catalogo', 'ProdutosController@catalogoPost')->name('catalogo.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('aplicacoes', 'AplicacoesController');
		Route::resource('certificados-e-homologacoes', 'CertificadosEHomologacoesController');
		Route::resource('aviso-home', 'AvisoHomeController', ['only' => ['index', 'update']]);
        Route::resource('cases-e-obras', 'CasesEObrasController');
        Route::get('cases-e-obras/{cases_e_obras}/imagens/clear', [
            'as'   => 'painel.cases-e-obras.imagens.clear',
            'uses' => 'CasesEObrasImagensController@clear'
        ]);
        Route::resource('cases-e-obras.imagens', 'CasesEObrasImagensController', ['parameters' => ['imagens' => 'imagens_cases-e-obras']]);
		Route::resource('produtos/catalogos', 'ProdutosCatalogosController');
		//Route::resource('produtos/segmentos', 'ProdutosSegmentosController', ['parameters' => ['segmentos' => 'segmentos_produtos']]);
		Route::resource('produtos/linhas', 'ProdutosLinhasController', ['parameters' => ['linhas' => 'linhas_produtos']]);
		Route::resource('produtos', 'ProdutosController');
        Route::resource('blog/categorias', 'BlogCategoriasController');
        Route::resource('blog', 'BlogPostsController');
        Route::get('blog/{blog}/comentarios/{comentarios}/aprovacao', 'BlogComentariosController@aprovacao')->name('painel.blog.comentarios.aprovacao');
        Route::resource('blog.comentarios', 'BlogComentariosController');
		Route::resource('tabelas-apresentacao', 'TabelasApresentacaoController', ['only' => ['index', 'update']]);
		Route::resource('tabelas', 'TabelasController');
		Route::resource('clientes/categorias', 'ClientesCategoriasController', ['parameters' => ['categorias' => 'categorias_clientes']]);
		Route::resource('clientes', 'ClientesController');
		Route::resource('servicos', 'ServicosController');
		Route::resource('evolucao-dos-catalogos', 'EvolucaoDosCatalogosController');
		Route::resource('evolucao-da-marca', 'EvolucaoDaMarcaController');
		Route::resource('empresa', 'EmpresaController', ['only' => ['index', 'update']]);
		Route::resource('chamadas', 'ChamadasController', ['only' => ['index', 'update']]);
		Route::resource('financiamentos', 'FinanciamentosController');
		Route::resource('banners', 'BannersController');

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::get('contato/trabalhe-conosco/{trabalhe_conosco}/toggle', ['as' => 'painel.contato.trabalhe-conosco.toggle', 'uses' => 'TrabalheConoscoController@toggle']);
        Route::resource('contato/trabalhe-conosco', 'TrabalheConoscoController');
        Route::get('contato/pesquisa-de-satisfacao/{pesquisa_de_satisfacao}/toggle', ['as' => 'painel.contato.pesquisa-de-satisfacao.toggle', 'uses' => 'PesquisaController@toggle']);
        Route::resource('contato/pesquisa-de-satisfacao', 'PesquisaController');
        Route::resource('contato', 'ContatoController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests\BlogComentariosRequest;

use App\Models\BlogPost;
use App\Models\BlogCategoria;

use App\Models\Contato;

class BlogController extends Controller
{
    public function __construct()
    {
        $categorias = BlogCategoria::ordenados()->get();
        $arquivos   = BlogPost::select(\DB::raw('YEAR(data) as ano, MONTH(data) as mes'))
                               ->groupBy('ano', 'mes')
                               ->orderBy('ano', 'DESC')
                               ->orderBy('mes', 'DESC')
                               ->get();

        view()->share('categorias', $categorias);
        view()->share('arquivos', $arquivos);
    }

    public function arquivo($ano = null, $mes = null)
    {
        if (!$ano || !$mes) abort('404');

        $posts = BlogPost::ordenados()
                   ->whereRaw("YEAR(data) = $ano AND MONTH(data) = $mes")
                   ->get();

        return view('frontend.blog.lista', compact('posts', 'ano', 'mes'));
    }

    public function categoria(BlogCategoria $categoria)
    {
        $posts = $categoria->posts;

        return view('frontend.blog.lista', compact('posts', 'categoria'));
    }

    public function index(BlogPost $post)
    {
        if (!$post->exists) {
            $post = BlogPost::ordenados()->first();
        }

        $data_post = \Carbon\Carbon::createFromFormat('d/m/Y', $post->data)->format('Y-m-d');

        $anterior = BlogPost::select('slug')
                          ->where('data', '<', $data_post)
                          ->orWhere(function($query) use ($data_post, $post) {
                              $query->where('data', $data_post)
                                    ->where('id', '<', $post->id);
                          })
                          ->orderBy('data', 'DESC')
                          ->orderBy('id', 'DESC')
                          ->first();

        $proximo = BlogPost::select('slug')
                          ->where('data', '>', $data_post)
                          ->orWhere(function($query) use ($data_post, $post) {
                              $query->where('data', $data_post)
                                    ->where('id', '>', $post->id);
                          })
                          ->orderBy('data', 'ASC')
                          ->orderBy('id', 'ASC')
                          ->first();

        $data = [
            'post'     => $post,
            'proximo'  => $proximo ? $proximo->slug : null,
            'anterior' => $anterior ? $anterior->slug : null
        ];

        return view('frontend.blog.index', $data);
    }

    public function comentario(BlogComentariosRequest $request)
    {
        try {

            $post = BlogPost::findOrFail($request->get('post'));
            $post->comentarios()->create($request->except('post'));

            $contato = Contato::first();

            if (isset($contato->email)) {
                \Mail::send('emails.comentario', [
                    'comentario' => $request->all(),
                    'post'       => $post
                ], function($message) use ($request, $contato) {
                    $message->to($contato->email, config('site.name'))
                            ->subject('[NOVO COMENTÁRIO] '.config('site.name'));
                });
            }

        } catch (\Exception $e) {
            $response = [
                'message' => 'Ocorreu um erro. Tente novamente.'
            ];

            return response()->json($response);

        }

        $response = [
            'success' => true,
            'message' => 'Comentário enviado com sucesso. Sujeito à aprovação da moderação.'
        ];

        return response()->json($response);
    }
}

laravel/resources/views/painel/blog/categorias/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Blog / Categorias /</small> Adicionar Categoria</h2>
    </legend>

    {!! Form::open(['route' => 'painel.blog.categorias.store', 'files' => true]) !!}

        @include('painel.blog.categorias.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/blog/categorias/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Blog / Categorias /</small> Editar Categoria</h2>
    </legend>

    {!! Form::model($registro, [
        'route'  => ['painel.blog.categorias.update', $registro->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.blog.categorias.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/blog/categorias/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('titulo', 'Título') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.blog.categorias.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/blog/categorias/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <a href="{{ route('painel.blog.index') }}" class="btn btn-default btn-sm">
        &larr; Voltar para o Blog
    </a>

    <legend>
        <h2>
            <small>Blog /</small> Categorias
            <a href="{{ route('painel.blog.categorias.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Categoria</a>
        </h2>
    </legend>

    @if(!count($registros))
    <div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="blog_categorias">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Título</th>
                <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)
            <tr class="tr-row" id="{{ $registro->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td>{{ $registro->titulo }}</td>
                <td class="crud-actions">
                    {!! Form::open([
                        'route'  => ['painel.blog.categorias.destroy', $registro->id],
                        'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.blog.categorias.edit', $registro->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>


    @endif

@endsection