laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('empresa', 'EmpresaController@index')->name('empresa');
    Route::get('produtos/aplicacoes/{id?}', 'ProdutosController@aplicacoes')->name('produtos.aplicacoes');
    // Route::get('produtos/segmento/{produtos_segmento}', 'ProdutosController@segmento')->name('produtos.segmento');
    Route::get('produtos/{produtos_linha?}', 'ProdutosController@index')->name('produtos');
    Route::get('produtos/{produtos_linha}/{produto_slug}', 'ProdutosController@show')->name('produtos.show');
    Route::get('servicos/{servico_slug?}', 'ServicosController@index')->name('servicos');
    Route::get('cases-e-obras/{case_slug?}', 'CasesController@index')->name('cases');
    Route::get('clientes/{clientes_categoria?}', 'ClientesController@index')->name('clientes');
    Route::get('tabelas', 'TabelasController@index')->name('tabelas');
    Route::get('blog/{post_slug?}', 'BlogController@index')->name('blog');
    Route::get('blog/c/{blog_categoria}', 'BlogController@categoria')->name('blog.categoria');
    Route::get('blog/a/{ano}/{mes}', 'BlogController@arquivo')->name('blog.arquivo');
    Route::post('blog-comentario', 'BlogController@comentario');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::get('pesquisa-de-satisfacao', 'PesquisaController@index')->name('pesquisa');
    Route::post('pesquisa-de-satisfacao', 'PesquisaController@post')->name('pesquisa.post');
    Route::get('trabalhe-conosco', 'TrabalheConoscoController@index')->name('trabalhe');
    Route::post('trabalhe-conosco', 'TrabalheConoscoController@post')->name('trabalhe.post');
    Route::get('catalogo/{id}', 'ProdutosController@catalogo')->name('catalogo');
    Route::post('catalogo', 'ProdutosController@catalogoPost')->name('catalogo.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('aplicacoes', 'AplicacoesController');
		Route::resource('certificados-e-homologacoes', 'CertificadosEHomologacoesController');
		Route::resource('aviso-home', 'AvisoHomeController', ['only' => ['index', 'update']]);
        Route::resource('cases-e-obras', 'CasesEObrasController');
        Route::get('cases-e-obras/{cases_e_obras}/imagens/clear', [
            'as'   => 'painel.cases-e-obras.imagens.clear',
            'uses' => 'CasesEObrasImagensController@clear'
        ]);
        Route::resource('cases-e-obras.imagens', 'CasesEObrasImagensController', ['parameters' => ['imagens' => 'imagens_cases-e-obras']]);
		Route::resource('produtos/catalogos', 'ProdutosCatalogosController');
		//Route::resource('produtos/segmentos', 'ProdutosSegmentosController', ['parameters' => ['segmentos' => 'segmentos_produtos']]);
		Route::resource('produtos/linhas', 'ProdutosLinhasController', ['parameters' => ['linhas' => 'linhas_produtos']]);
		Route::resource('produtos', 'ProdutosController');
        Route::resource('blog/categorias', 'BlogCategoriasController');
        Route::resource('blog', 'BlogPostsController');
        Route::get('blog/{blog}/comentarios/{comentarios}/aprovacao', 'BlogComentariosController@aprovacao')->name('painel.blog.comentarios.aprovacao');
        Route::resource('blog.comentarios', 'BlogComentariosController');
		Route::resource('tabelas-apresentacao', 'TabelasApresentacaoController', ['only' => ['index', 'update']]);
		Route::resource('tabelas', 'TabelasController');
		Route::resource('clientes/categorias', 'ClientesCategoriasController', ['parameters' => ['categorias' => 'categorias_clientes']]);
		Route::resource('clientes', 'ClientesController');
		Route::resource('servicos', 'ServicosController');
		Route::resource('evolucao-dos-catalogos', 'EvolucaoDosCatalogosController');
		Route::resource('evolucao-da-marca', 'EvolucaoDaMarcaController');
		Route::resource('empresa', 'EmpresaController', ['only' => ['index', 'update']]);
		Route::resource('chamadas', 'ChamadasController', ['only' => ['index', 'update']]);
		Route::resource('financiamentos', 'FinanciamentosController');
		Route::resource('banners', 'BannersController');

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::get('contato/trabalhe-conosco/{trabalhe_conosco}/toggle', ['as' => 'painel.contato.trabalhe-conosco.toggle', 'uses' => 'TrabalheConoscoController@toggle']);
        Route::resource('contato/trabalhe-conosco', 'TrabalheConoscoController');
        Route::get('contato/pesquisa-de-satisfacao/{pesquisa_de_satisfacao}/toggle', ['as' => 'painel.contato.pesquisa-de-satisfacao.toggle', 'uses' => 'PesquisaController@toggle']);
        Route::resource('contato/pesquisa-de-satisfacao', 'PesquisaController');
        Route::resource('contato', 'ContatoController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/ClientesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Models\ClienteCategoria;
use App\Models\Cliente;

class ClientesController extends Controller
{
    public function index(ClienteCategoria $categoria)
    {
        $categorias = ClienteCategoria::ordenados()->get();

        if (!$categoria->exists) {
            $categoria = ClienteCategoria::ordenados()->first();
        }

        return view('frontend.clientes', compact('categorias', 'categoria'));
    }
}

laravel/app/Http/Controllers/Painel/AplicacoesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AplicacoesRequest;
use App\Http\Controllers\Controller;

use App\Models\Aplicacao;

class AplicacoesController extends Controller
{
    public function index()
    {
        $registros = Aplicacao::ordenados()->get();

        return view('painel.aplicacoes.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.aplicacoes.create');
    }

    public function store(AplicacoesRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Aplicacao::upload_imagem();

            Aplicacao::create($input);

            return redirect()->route('painel.aplicacoes.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Aplicacao $registro)
    {
        return view('painel.aplicacoes.edit', compact('registro'));
    }

    public function update(AplicacoesRequest $request, Aplicacao $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Aplicacao::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.aplicacoes.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Aplicacao $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.aplicacoes.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/AvisoHomeController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AvisoHomeRequest;
use App\Http\Controllers\Controller;

use App\Models\AvisoHome;

class AvisoHomeController extends Controller
{
    public function index()
    {
        $registro = AvisoHome::first();

        return view('painel.aviso-home.edit', compact('registro'));
    }

    public function update(AvisoHomeRequest $request, AvisoHome $registro)
    {
        try {
            $input = $request->all();


            $registro->update($input);

            return redirect()->route('painel.aviso-home.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/BlogCategoriasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BlogCategoriasRequest;
use App\Http\Controllers\Controller;

use App\Models\BlogCategoria;

class BlogCategoriasController extends Controller
{
    public function index()
    {
        $registros = BlogCategoria::ordenados()->get();

        return view('painel.blog.categorias.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.blog.categorias.create');
    }

    public function store(BlogCategoriasRequest $request)
    {
        try {

            $input = $request->all();


            BlogCategoria::create($input);
            return redirect()->route('painel.blog.categorias.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(BlogCategoria $registro)
    {
        return view('painel.blog.categorias.edit', compact('registro'));
    }

    public function update(BlogCategoriasRequest $request, BlogCategoria $registro)
    {
        try {

            $input = $request->all();


            $registro->update($input);
            return redirect()->route('painel.blog.categorias.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(BlogCategoria $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.blog.categorias.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/BlogComentariosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\BlogPost;
use App\Models\BlogComentario;

class BlogComentariosController extends Controller
{
    public function index(BlogPost $post)
    {
        $registros = $post->comentarios;

        return view('painel.blog.comentarios', compact('post', 'registros'));
    }

    public function destroy(BlogPost $post, BlogComentario $comentario)
    {
        try {

            $comentario->delete();
            return redirect()->back()->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

    public function aprovacao(BlogPost $post, BlogComentario $comentario)
    {
        try {

            $comentario->update([
                'aprovado' => !$comentario->aprovado
            ]);
            return redirect()->back()->with('success', 'Status atualizado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao atualizar status: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/BlogPostsController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BlogPostsRequest;
use App\Http\Controllers\Controller;

use App\Models\BlogPost;
use App\Models\BlogCategoria;

class BlogPostsController extends Controller
{
    public function __construct()
    {
        view()->share([
            'categorias' => BlogCategoria::ordenados()->lists('titulo', 'id')
        ]);
    }

    public function index()
    {
        $registros = BlogPost::ordenados()->paginate(10);

        return view('painel.blog.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.blog.create');
    }

    public function store(BlogPostsRequest $request)
    {
        try {

            $input = $request->all();

            BlogPost::create($input);
            return redirect()->route('painel.blog.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(BlogPost $registro)
    {
        return view('painel.blog.edit', compact('registro'));
    }

    public function update(BlogPostsRequest $request, BlogPost $registro)
    {
        try {

            $input = $request->all();

            $registro->update($input);
            return redirect()->route('painel.blog.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(BlogPost $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.blog.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ChamadasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ChamadasRequest;
use App\Http\Controllers\Controller;

use App\Models\Chamadas;

class ChamadasController extends Controller
{
    public function index()
    {
        $registro = Chamadas::first();

        return view('painel.chamadas.edit', compact('registro'));
    }

    public function update(ChamadasRequest $request, Chamadas $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_1'])) $input['imagem_1'] = Chamadas::upload_imagem_1();
            if (isset($input['imagem_2'])) $input['imagem_2'] = Chamadas::upload_imagem_2();

            $registro->update($input);

            return redirect()->route('painel.chamadas.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/clientes/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Clientes /</small> Adicionar Cliente</h2>
    </legend>

    {!! Form::open(['route' => 'painel.clientes.store', 'files' => true]) !!}

        @include('painel.clientes.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/clientes/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Clientes /</small> Editar Cliente</h2>
    </legend>

    {!! Form::model($registro, [
        'route'  => ['painel.clientes.update', $registro->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.clientes.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/clientes/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('clientes_categoria_id', 'Categoria') !!}
    {!! Form::select('clientes_categoria_id', $categorias, null, ['class' => 'form-control', 'placeholder' => 'Selecione']) !!}
</div>

<div class="well form-group">
    {!! Form::label('imagem', 'Imagem') !!}
@if($submitText == 'Alterar')
    <img src="{{ url('assets/img/clientes/'.$registro->imagem) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
@endif
    {!! Form::file('imagem', ['class' => 'form-control']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.clientes.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/clientes/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <legend>
        <h2>
            Clientes
            <a href="{{ route('painel.clientes.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Cliente</a>
        </h2>
    </legend>

    <div class="row" style="margin-bottom:20px">
        <div class="form-group col-sm-4">
            {!! Form::select('filtro', $categorias, Request::get('filtro'), ['class' => 'form-control', 'id' => 'filtro-select', 'placeholder' => 'Todas as Categorias', 'data-route' => 'painel/clientes']) !!}
        </div>
        <div class="col-sm-4" style="padding-left:0">
        <a href="{{ route('painel.clientes.categorias.index') }}" class="btn btn-primary btn-md"><span class="glyphicon glyphicon-edit" style="margin-right:10px;"></span><small>Editar Categorias</small></a>
        </div>
        @if(!$filtro)
        <div class="col-sm-4">
            <p class="alert alert-info small" style="margin-bottom: 15px; height:45px; padding: 12px 15px;">
                <span class="glyphicon glyphicon-info-sign" style="margin-right:10px;"></span>
                Selecione uma categoria para ordenar os registros.
            </p>
        </div>
        @endif
    </div>

    @if(!count($registros))
    <div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="clientes">
        <thead>
            <tr>
                @if($filtro)<th>Ordenar</th>@endif
                @if(!$filtro)<th>Categoria</th>@endif
                <th>Imagem</th>
                <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)
            <tr class="tr-row" id="{{ $registro->id }}">
                @if($filtro)
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                @endif
                @if(!$filtro)
                <td>
                    @if($registro->categoria)
                    {{ $registro->categoria->titulo }}
                    @else
                    <span class="label label-warning">sem categoria</span>
                    @endif
                </td>
                @endif
                <td><img src="{{ asset('assets/img/clientes/'.$registro->imagem) }}" style="width: 100%; max-width:150px;" alt=""></td>
                <td class="crud-actions">
                    {!! Form::open([
                        'route'  => ['painel.clientes.destroy', $registro->id],
                        'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.clientes.edit', $registro->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @endif

@endsection