laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('empresa', 'EmpresaController@index')->name('empresa');
    Route::get('produtos/aplicacoes/{id?}', 'ProdutosController@aplicacoes')->name('produtos.aplicacoes');
    // Route::get('produtos/segmento/{produtos_segmento}', 'ProdutosController@segmento')->name('produtos.segmento');
    Route::get('produtos/{produtos_linha?}', 'ProdutosController@index')->name('produtos');
    Route::get('produtos/{produtos_linha}/{produto_slug}', 'ProdutosController@show')->name('produtos.show');
    Route::get('servicos/{servico_slug?}', 'ServicosController@index')->name('servicos');
    Route::get('cases-e-obras/{case_slug?}', 'CasesController@index')->name('cases');
    Route::get('clientes/{clientes_categoria?}', 'ClientesController@index')->name('clientes');
    Route::get('tabelas', 'TabelasController@index')->name('tabelas');
    Route::get('blog/{post_slug?}', 'BlogController@index')->name('blog');
    Route::get('blog/c/{blog_categoria}', 'BlogController@categoria')->name('blog.categoria');
    Route::get('blog/a/{ano}/{mes}', 'BlogController@arquivo')->name('blog.arquivo');
    Route::post('blog-comentario', 'BlogController@comentario');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::get('pesquisa-de-satisfacao', 'PesquisaController@index')->name('pesquisa');
    Route::post('pesquisa-de-satisfacao', 'PesquisaController@post')->name('pesquisa.post');
    Route::get('trabalhe-conosco', 'TrabalheConoscoController@index')->name('trabalhe');
    Route::post('trabalhe-conosco', 'TrabalheConoscoController@post')->name('trabalhe.post');
    Route::get('catalogo/{id}', 'ProdutosController@catalogo')->name('catalogo');
    Route::post('catalogo', 'ProdutosController@catalogoPost')->name('catalogo.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('aplicacoes', 'AplicacoesController');
		Route::resource('certificados-e-homologacoes', 'CertificadosEHomologacoesController');
		Route::resource('aviso-home', 'AvisoHomeController', ['only' => ['index', 'update']]);
        Route::resource('cases-e-obras', 'CasesEObrasController');
        Route::get('cases-e-obras/{cases_e_obras}/imagens/clear', [
            'as'   => 'painel.cases-e-obras.imagens.clear',
            'uses' => 'CasesEObrasImagensController@clear'
        ]);
        Route::resource('cases-e-obras.imagens', 'CasesEObrasImagensController', ['parameters' => ['imagens' => 'imagens_cases-e-obras']]);
		Route::resource('produtos/catalogos', 'ProdutosCatalogosController');
		//Route::resource('produtos/segmentos', 'ProdutosSegmentosController', ['parameters' => ['segmentos' => 'segmentos_produtos']]);
		Route::resource('produtos/linhas', 'ProdutosLinhasController', ['parameters' => ['linhas' => 'linhas_produtos']]);
		Route::resource('produtos', 'ProdutosController');
        Route::resource('blog/categorias', 'BlogCategoriasController');
        Route::resource('blog', 'BlogPostsController');
        Route::get('blog/{blog}/comentarios/{comentarios}/aprovacao', 'BlogComentariosController@aprovacao')->name('painel.blog.comentarios.aprovacao');
        Route::resource('blog.comentarios', 'BlogComentariosController');
		Route::resource('tabelas-apresentacao', 'TabelasApresentacaoController', ['only' => ['index', 'update']]);
		Route::resource('tabelas', 'TabelasController');
		Route::resource('clientes/categorias', 'ClientesCategoriasController', ['parameters' => ['categorias' => 'categorias_clientes']]);
		Route::resource('clientes', 'ClientesController');
		Route::resource('servicos', 'ServicosController');
		Route::resource('evolucao-dos-catalogos', 'EvolucaoDosCatalogosController');
		Route::resource('evolucao-da-marca', 'EvolucaoDaMarcaController');
		Route::resource('empresa', 'EmpresaController', ['only' => ['index', 'update']]);
		Route::resource('chamadas', 'ChamadasController', ['only' => ['index', 'update']]);
		Route::resource('financiamentos', 'FinanciamentosController');
		Route::resource('banners', 'BannersController');

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::get('contato/trabalhe-conosco/{trabalhe_conosco}/toggle', ['as' => 'painel.contato.trabalhe-conosco.toggle', 'uses' => 'TrabalheConoscoController@toggle']);
        Route::resource('contato/trabalhe-conosco', 'TrabalheConoscoController');
        Route::get('contato/pesquisa-de-satisfacao/{pesquisa_de_satisfacao}/toggle', ['as' => 'painel.contato.pesquisa-de-satisfacao.toggle', 'uses' => 'PesquisaController@toggle']);
        Route::resource('contato/pesquisa-de-satisfacao', 'PesquisaController');
        Route::resource('contato', 'ContatoController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/AplicacoesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AplicacoesRequest;
use App\Http\Controllers\Controller;

use App\Models\Aplicacao;

class AplicacoesController extends Controller
{
    public function index()
    {
        $registros = Aplicacao::ordenados()->get();

        return view('painel.aplicacoes.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.aplicacoes.create');
    }

    public function store(AplicacoesRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Aplicacao::upload_imagem();

            Aplicacao::create($input);

            return redirect()->route('painel.aplicacoes.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Aplicacao $registro)
    {
        return view('painel.aplicacoes.edit', compact('registro'));
    }

    public function update(AplicacoesRequest $request, Aplicacao $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Aplicacao::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.aplicacoes.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Aplicacao $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.aplicacoes.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/AvisoHomeController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AvisoHomeRequest;
use App\Http\Controllers\Controller;

use App\Models\AvisoHome;

class AvisoHomeController extends Controller
{
    public function index()
    {
        $registro = AvisoHome::first();

        return view('painel.aviso-home.edit', compact('registro'));
    }

    public function update(AvisoHomeRequest $request, AvisoHome $registro)
    {
        try {
            $input = $request->all();


            $registro->update($input);

            return redirect()->route('painel.aviso-home.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/BlogCategoriasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BlogCategoriasRequest;
use App\Http\Controllers\Controller;

use App\Models\BlogCategoria;

class BlogCategoriasController extends Controller
{
    public function index()
    {
        $registros = BlogCategoria::ordenados()->get();

        return view('painel.blog.categorias.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.blog.categorias.create');
    }

    public function store(BlogCategoriasRequest $request)
    {
        try {

            $input = $request->all();


            BlogCategoria::create($input);
            return redirect()->route('painel.blog.categorias.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(BlogCategoria $registro)
    {
        return view('painel.blog.categorias.edit', compact('registro'));
    }

    public function update(BlogCategoriasRequest $request, BlogCategoria $registro)
    {
        try {

            $input = $request->all();


            $registro->update($input);
            return redirect()->route('painel.blog.categorias.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(BlogCategoria $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.blog.categorias.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/BlogComentariosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\BlogPost;
use App\Models\BlogComentario;

class BlogComentariosController extends Controller
{
    public function index(BlogPost $post)
    {
        $registros = $post->comentarios;

        return view('painel.blog.comentarios', compact('post', 'registros'));
    }

    public function destroy(BlogPost $post, BlogComentario $comentario)
    {
        try {

            $comentario->delete();
            return redirect()->back()->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

    public function aprovacao(BlogPost $post, BlogComentario $comentario)
    {
        try {

            $comentario->update([
                'aprovado' => !$comentario->aprovado
            ]);
            return redirect()->back()->with('success', 'Status atualizado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao atualizar status: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/BlogPostsController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BlogPostsRequest;
use App\Http\Controllers\Controller;

use App\Models\BlogPost;
use App\Models\BlogCategoria;

class BlogPostsController extends Controller
{
    public function __construct()
    {
        view()->share([
            'categorias' => BlogCategoria::ordenados()->lists('titulo', 'id')
        ]);
    }

    public function index()
    {
        $registros = BlogPost::ordenados()->paginate(10);

        return view('painel.blog.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.blog.create');
    }

    public function store(BlogPostsRequest $request)
    {
        try {

            $input = $request->all();

            BlogPost::create($input);
            return redirect()->route('painel.blog.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(BlogPost $registro)
    {
        return view('painel.blog.edit', compact('registro'));
    }

    public function update(BlogPostsRequest $request, BlogPost $registro)
    {
        try {

            $input = $request->all();

            $registro->update($input);
            return redirect()->route('painel.blog.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(BlogPost $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.blog.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ChamadasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ChamadasRequest;
use App\Http\Controllers\Controller;

use App\Models\Chamadas;

class ChamadasController extends Controller
{
    public function index()
    {
        $registro = Chamadas::first();

        return view('painel.chamadas.edit', compact('registro'));
    }

    public function update(ChamadasRequest $request, Chamadas $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_1'])) $input['imagem_1'] = Chamadas::upload_imagem_1();
            if (isset($input['imagem_2'])) $input['imagem_2'] = Chamadas::upload_imagem_2();

            $registro->update($input);

            return redirect()->route('painel.chamadas.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/header.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url('/') }}">{{ config('site.name') }}</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            @include('painel.common.nav')

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown @if(str_is('painel.usuarios*', Route::currentRouteName())) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('painel.usuarios.index') }}">Usuários</a></li>
                        <li><a href="{{ route('logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">
    <li class="dropdown @if(str_is('painel.banners*', Route::currentRouteName()) || str_is('painel.chamadas*', Route::currentRouteName()) || str_is('painel.financiamentos*', Route::currentRouteName()) || str_is('painel.aviso-home*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Home
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.aviso-home*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.aviso-home.index') }}">Aviso Home</a>
            </li>
            <li @if(str_is('painel.banners*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.banners.index') }}">Banners</a>
            </li>
            <li @if(str_is('painel.chamadas*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.chamadas.index') }}">Chamadas</a>
            </li>
            <li @if(str_is('painel.financiamentos*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.financiamentos.index') }}">Financiamentos</a>
            </li>
        </ul>
    </li>
    <li class="dropdown @if(str_is('painel.empresa*', Route::currentRouteName()) || str_is('painel.evolucao-dos-catalogos*', Route::currentRouteName()) || str_is('painel.evolucao-da-marca*', Route::currentRouteName()) || str_is('painel.certificados-e-homologacoes*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Empresa
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.empresa*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.empresa.index') }}">Empresa</a>
            </li>
            <li @if(str_is('painel.evolucao-da-marca*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.evolucao-da-marca.index') }}">Evolução da Marca</a>
            </li>
            <li @if(str_is('painel.evolucao-dos-catalogos*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.evolucao-dos-catalogos.index') }}">Evolução dos Catálogos</a>
            </li>
            <li @if(str_is('painel.certificados-e-homologacoes*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.certificados-e-homologacoes.index') }}">Certificados e Homologações</a>
            </li>
        </ul>
    </li>
    <li @if(str_is('painel.produtos*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.produtos.index') }}">Produtos</a>
    </li>
	<li @if(str_is('painel.aplicacoes*', Route::currentRouteName())) class="active" @endif>
		<a href="{{ route('painel.aplicacoes.index') }}">Aplicações</a>
	</li>
    <li @if(str_is('painel.servicos*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.servicos.index') }}">Serviços</a>
    </li>
	<li @if(str_is('painel.cases-e-obras*', Route::currentRouteName())) class="active" @endif>
		<a href="{{ route('painel.cases-e-obras.index') }}">Cases e Obras</a>
	</li>
    <li @if(str_is('painel.clientes*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.clientes.index') }}">Clientes</a>
    </li>
	<li @if(str_is('painel.tabelas*', Route::currentRouteName())) class="active" @endif>
		<a href="{{ route('painel.tabelas.index') }}">Tabelas</a>
	</li>
    <li @if(str_is('painel.blog*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.blog.index') }}">Blog</a>
    </li>
    <li class="dropdown @if(str_is('painel.contato*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($totalNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $totalNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ route('painel.contato.index') }}">Informações de Contato</a></li>
            <li><a href="{{ route('painel.contato.recebidos.index') }}">
                Contatos Recebidos
                @if($contatosNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                @endif
            </a></li>
            <li><a href="{{ route('painel.contato.trabalhe-conosco.index') }}">
                Trabalhe Conosco
                @if($trabalheNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $trabalheNaoLidos }}</span>
                @endif
            </a></li>
            <li><a href="{{ route('painel.contato.pesquisa-de-satisfacao.index') }}">
                Pesquisa de Satisfação
                @if($pesquisaNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $pesquisaNaoLidos }}</span>
                @endif
            </a></li>
        </ul>
    </li>
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('site.name') }} - Painel Administrativo</title>

    {!! Tools::loadCss('vendor/bootswatch-dist/css/bootstrap.min.css') !!}
    {!! Tools::loadCss('vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') !!}
    {!! Tools::loadCss('css/vendor.painel.css') !!}
    {!! Tools::loadCss('css/painel.css') !!}
</head>
<body>
    @include('painel.common.header')

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    {!! Tools::loadJquery() !!}
    {!! Tools::loadJs('vendor/ckeditor/ckeditor.js') !!}
    {!! Tools::loadJs('js/vendor.painel.js') !!}
    {!! Tools::loadJs('js/painel.js') !!}
</body>
</html>